In [1]:
import numpy as np



In [2]:
arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)      # (2, 3)
print(arr.dtype)    


In [3]:
arr = np.arange(9)
reshaped = arr.reshape((3, 3))
print(reshaped)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
arr = np.array([5, 3, 8, 1])
sorted_arr = np.sort(arr)
print(sorted_arr) 


[1 3 5 8]


In [5]:
zeros = np.zeros((3, 3))
print(zeros)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
rand_arr = np.random.rand(2, 2)
print(rand_arr)


[[0.68929625 0.42401001]
 [0.10234447 0.88457083]]


In [7]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
transposed = np.transpose(arr)
print(transposed)


[[1 3 5]
 [2 4 6]]


In [8]:
arr = np.array([1, 2, 3, 4, 5])
normalized = (arr - np.mean(arr)) / np.std(arr)
print(normalized)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertically
v_stack = np.vstack((arr1, arr2))
print(v_stack)

# Horizontally
h_stack = np.hstack((arr1, arr2))
print(h_stack)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
